apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8stutorial-com-tls
spec:
  secretName: k8stutorial-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8stutorial.com
  dnsNames:
    - k8stutorial.com
    - www.k8stutorial.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8stutorial.com
          - www.k8stutorial.com